/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 model3.gltf --transform 
Files: model3.gltf [5.86KB] > model3-transformed.glb [2.5KB] (57%)
Author: Fyrestar (https://sketchfab.com/mevedia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/threejs-60320862bf904b7ab0e032c27daf7c7c
Title: Three.js
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/model3-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh scale={0.5} geometry={nodes.Object_5.geometry} material={materials.material_0} />
    </group>
  )
}

useGLTF.preload('/model3-transformed.glb')
